rest:
  auth-open: false #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

server:
  port: 80 #项目端口

beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/rest/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.rest/**/model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/szlc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: Root2012!
      filters: log4j,wall,mergeStat
  mvc:
      static-path-pattern: /static/**
      view:
        prefix: /WEB-INF/view
  http:
      multipart:
        max-request-size: 10MB #最大请求大小
        max-file-size: 10MB #最大文件大小

logging:
  level.root: error
  level.com.stylefeng: error
  file: logs/rest.log

# APP项目自定义配置
app:
#  file-upload-path: file-upload-path: D:\work18\apache-tomcat-8.0.33\webapps\admin\WEB-INF\classes\static\upload\  #文件上传目录(不配置的话为java.io.tmpdir目录)
  file-upload-path: /root/apache-tomcat-pic/webapps/pictureServer/static/upload/
  picture-server-address: http://103.228.108.200:8585/pictureServer/static/upload/  #图片服务器地址
